# Generated by Django 4.0.2 on 2022-02-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artical',
            new_name='Article',
        ),
    ]
